.\" Manpage for torture
.\" Contact leitao@debian.org to correct errors or typos.
.TH man 1 "11 Nov 2017" "1.0" "torture man page"
.SH NAME
torture \- Hardware Transactional Memory stress tool
.SH SYNOPSIS
torture [-v] [-c <threads>] [-a|-c|-f] 
.SH DESCRIPTION
Torture is a tool to stress hardware transactional memory subsystem. It runs different workloads within an Transactional memory, and dump the statistics about failure.

It also garantees that the register set is not corrupted.
.SH OPTIONS
.B -a
\- Run all workloads
.PP
.B -c
\- Run only workloads that are supposed to commit
.PP
.B -f
\- Run only workloads that are supposed to fail
.PP
.B -v
\- Verbose output
.PP
.B -n 
.BI [threads]
\- Set the number of threads to be used
.PP
.B -h
\- Help
\" .SH SEE ALSO
\" TBD
.SH BUGS
No known bugs.
.SH AUTHOR
Breno Leitao (leitao@debian.org>
